[package]
name = "diesel_demo"
version = "0.1.0"
authors = ["apmechev <apmechev@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.6.5"
diesel = { version = "1.0.0", features = ["postgres"] }
dotenv = "0.9.0"
